// USER TYPES
export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

// DATA TYPES
export const SET_POSTS = "SET_POSTS";
export const ADD_POST = "ADD_POST";
export const REMOVE_POST = "REMOVE_POST";
export const SET_SINGLE_POST = "SET_SINGLE_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const ADD_LIKE = "ADD_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";

// UI TYPES
export const LOADING_UI_LOGIN = "LOADING_UI";
export const CLEAR_LOADING_UI_LOGIN = "CLEAR_LOADING_UI_LOGIN";
export const SET_ERRORS_LOGIN = "SET_ERRORS_LOGIN";
export const CLEAR_ERRORS_LOGIN = "CLEAR_ERRORS_LOGIN";
export const LOADING_UI_SIGNUP = "LOADING_UI_SIGNUP";
export const CLEAR_LOADING_UI_SIGNUP = "CLEAR_LOADING_UI_SIGNUP";
export const SET_ERRORS_SIGNUP = "SET_ERRORS_SIGNUP";
export const CLEAR_ERRORS_SIGNUP = "CLEAR_ERRORS_SIGNUP";
export const SET_SUCCESS_ALERT = "SET_SUCCESS_ALERT";
export const LOADING_POSTS = "LOADING_POSTS";
export const CLEAR_LOADING_POSTS = "CLEAR_LOADING_POSTS";
export const LOADING_USER = "LOADING_USER";
export const CLEAR_LOADING_USER = "CLEAR_LOADING_USER";
export const LOADING_ADD_POST = "LOADING_ADD_POST";
export const CLEAR_LOADING_ADD_POST = "CLEAR_LOADING_ADD_POST";
export const SET_ERRORS_ADD_POST = "SET_ERRORS_ADD_POST";
export const LOADING_SINGLE_POST = "LOADING_SINGLE_POST";
export const CLEAR_LOADING_SINGLE_POST = "CLEAR_LOADING_SINGLE_POST";
export const SET_POST_NOT_FOUND = "SET_POST_NOT_FOUND";
export const LOADING_ADD_COMMENT = "LOADING_ADD_COMMENT";
export const CLEAR_LOADING_ADD_COMMENT = "CLEAR_LOADING_ADD_COMMENT";
export const SET_ERRORS_NEW_COMMENT = "SET_ERROR_NEW_COMMENT";
export const CLEAR_ERROR_NEW_COMMENT = "CLEAR_ERROR_NEW_COMMENT";
export const SET_USER_NOT_FOUND = "SET_USER_NOT_FOUND";
export const LOADING_REMOVE_POST = "LOADING_REMOVE_POST";
export const CLEAR_LOADING_REMOVE_POST = "CLEAR_LOADING_REMOVE_POST";
export const LOADING_UPDATE_PROFILE = "LOADING_UPDATE_PROFILE";
export const CLEAR_LOADING_UPDATE_PROFILE = "CLEAR_LOADING_UPDATE_PROFILE";
export const SET_ERRORS_UPDATE_PROFILE = "SET_ERRORS_UPDATE_PROFILE";
export const CLEAR_SET_ERRORS_UPDATE_PROFILE =
  "CLEAR_SET_ERRORS_UPDATE_PROFILE";
