// USER TYPES
export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

// DATA TYPES
export const SET_POSTS = "SET_POSTS";

// UI TYPES
export const LOADING_UI_LOGIN = "LOADING_UI";
export const CLEAR_LOADING_UI_LOGIN = "CLEAR_LOADING_UI_LOGIN";
export const SET_ERRORS_LOGIN = "SET_ERRORS_LOGIN";
export const CLEAR_ERRORS_LOGIN = "CLEAR_ERRORS_LOGIN";
export const LOADING_UI_SIGNUP = "LOADING_UI_SIGNUP";
export const CLEAR_LOADING_UI_SIGNUP = "CLEAR_LOADING_UI_SIGNUP";
export const SET_ERRORS_SIGNUP = "SET_ERRORS_SIGNUP";
export const CLEAR_ERRORS_SIGNUP = "CLEAR_ERRORS_SIGNUP";
export const SET_SUCCESS_ALERT = "SET_SUCCESS_ALERT";
